### ISSUE TITLE
Bug with AmiraHyperSurfaceSegmentation

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [emdb-empiar/ahds#7] opened 2022-08-12 07:07 UTC
Dear all,

There is a bug with AmiraHyperSurfaceSegmentation:
```
app_spec_seg = AmiraHyperSurfaceSegmentation(filepath_str)
```
`filepath_str` is valid filename

```
Exception has occurred: ValueError will not overwrite attribute 'name'
```

**Comment by paulkorir** [comment] 2022-09-02 09:07
This is an exception that originates from `ahds`, the Python package used to read Amira files. I will close this here but open an issue in the `ahds` repository. Could you please give me a bit more details about the file? Perhaps if you can share it with me. You can find the issue at https://github.com/emdb-empiar/ahds/issues.

**Comment by aliaksei-chareshneu** [comment] 2022-09-03 15:41
@paulkorir, thank you. Here are both files I tried (they produced the same error):
[files.zip](https://github.com/emdb-empiar/ahds/files/9482925/files.zip)

**Comment by paulkorir** [comment] 2022-09-05 12:17
Yes, I can confirm that the problem is with how `ahds` handles them. Could you please give me some details about how these segmentations were generated?

**Comment by paulkorir** [comment] 2022-09-05 12:48
I've found the problem. I just need to try and figure out the best way to fix it without breaking other people's code.

**Comment by hernot** [comment] 2022-09-05 13:43
On a quick check i do see on the Material `Inside` name seems to be superfluous  as it reads `Inside` and on the Parameter `BoundaryIds` name reads `BoundaryConditions` but no further parameters there. Crosschecking with existing test files materials do have a name attribute when appearing in dedicate `Materials{{},{}}` list but not when occurring in `Parameters{Materials{}}`. So seems as if Materials were moved from `Materials`to `Parameter{Materials }` using Name to insert Material there but not deleting Name form the materials parameter list.

For now i would suggest to assume that extra name attribute is meant as alias name and simply add the bock a second time to its parent block using the alias name stated by `name` attribute. Would be the least invasive approach.    (*)

For final handling of the provided examples the following things would have to be further investigated. 

- What purpose serve the following parameters and Material parameters which i do fear will not be recognized by ahds and i would ony expect to be recognized by latest Amira or some add-on modules of modern Amira which are not yet supported by ahds. 

  * `BoundaryIds` : just contain name pointing to boundary Conditions without referring to any item in the further `HyperSurface` structure supported so far by AHDS. @paulkorir can you please check on the exampe files of your Amira copy if BoundaryIds is part of newer HyperSurface files. Up to Amira 5.x it isn't.
 
  * &Color: looks like a base 64 encoded string of some obscure data -> compare Color which encodes classical RGB triplet as described in manual. What purpose does it serve
  * &GridBox: looks like a base 64 encoded string of some obscure data -> compare GridBox which encodes a 3D bounding box. What Purpose does it serve.

- Is the name attribute an alias for the parameter or a rename for loading with newer versions of Amira or any of its addons.

**EDIT**
(*) In addition to add block under the specified alias an attribute aliases could be added  hosting the list of alias names this block can be accessed on its parent.  Especially later when writing will be enabled this can be helpful to not duplicate the block content but just store the alias name(s) under name parameter.

**Comment by paulkorir** [comment] 2022-09-06 09:39
@hernot We do have one example in the test dataset (`ahds/data/test7.surf`) which has the same `BoundaryIds { Name "BoundaryConditions" }` but the difference is the case (`Name` vs `name`). I'm not sure whether the file was modified (if I understood what you said correctly). As for the `&Colour`, we do have an example files (`ahds/data/EM04226_2_U19_Cropped_YZ_binned.labels.am` but none for `&GridBox`. In any event, these are handled fine. 
The problem is that we use a `name` attribute and these files prove that it is likely to happen. `name` is a _fundamental_ attribute and adding an alias may not be the right solution. 
You raise valid questions but here's the big picture: I think we should support _any_ version regardless of how modern or ancient they are. As long as Amira continue to use the VRML-like syntax then we can always dance our way around the header grammar.
Question: do you use `Block` or `ListBlock` classes anywhere directly? If you don't then the changes that I'm proposing (`.name` to `.block_name`) will be completely tranparent - you will never notice it. I've made these changes in a bugfix branch which I will push shortly - I think all tests pass without issue. 
Let me know...

**Comment by paulkorir** [comment] 2022-09-06 11:21
It's all on `bugfix-issue7` -> https://github.com/emdb-empiar/ahds/tree/bugfix-issue7

**Comment by hernot** [comment] 2022-09-06 13:09
As this is to me more a matter of loading logic than general file structure, i'd prefer to amend in header.py `Header._load_pameters` method by expanding lines 329 - 340 to be aware of the possibility that parameters might have an alias name instead of over complicating `Block.add_attr` method.

I can come up tonight with a pr suggesting  how this would look like.

**Comment by paulkorir** [comment] 2022-09-06 15:23
I see what you mean. I'll wait to see your PR. Thank you very much.

**Comment by hernot** [comment] 2022-09-06 20:01
The relevant part is in `header.py` and i had to amend all `Block__str__` and `<SubBlock>.__str__` methods to be aware of the possibility of block being aliased. The rest are rerverts to master.

**Comment by paulkorir** [comment] 2022-09-07 08:08
I'll take a look. Thank you.

**Comment by aliaksei-chareshneu** [comment] 2022-09-07 11:48
> Yes, I can confirm that the problem is with how `ahds` handles them. Could you please give me some details about how these segmentations were generated?

@paulkorir, if this information is still relevant - I created both using Amira software, as far as I remember, just using Thresholding tool. The segmentations themselves does not make much sense, I selected some random threshold just for testing purposes.

**Comment by aliaksei-chareshneu** [comment] 2022-09-07 11:49
@paulkorir, @hernot, thank you very much for addressing this issue in a promptly manner.
Please let me know if there is anything I can help with or further clarify to resolve the issue.

**Comment by hernot** [comment] 2022-09-07 15:49
@aliaksei-chareshneu just for the stats records would you happen to remember which version of Amira you created these files?

**Comment by aliaksei-chareshneu** [comment] 2022-09-08 07:41
> @aliaksei-chareshneu just for the stats records would you happen to remember which version of Amira you created these files?

Version 2022.1

**Comment by hernot** [comment] 2022-09-13 18:35
@aliaksei-chareshneu 
Can you do me/us a favor and also thumb-up the pull request  [#15](https://github.com/mcfletch/simpleparse/pull/15) on [mfletch/simpleparse](https://github.com/mcfletch/simpleparse) repo. Apart from future ahds releases using simple parse instead manual crafted HyperSurface file parsing, implementation of aliases and alike issues and  alike would be greatly simplified.

**Comment by paulkorir** [comment] 2022-09-26 13:09
I'm afraid we are stuck from making a release until mcfletch makes an ahds release from master which has the changes from v2.2.2. However, you can still install an up-to-date version using `pip install git+https://github.com/emdb-empiar/ahds`.

**Closed as completed by paulkorir** 2022-09-26 13:09 UTC

**Comment by hernot** [comment] 2022-09-26 15:13
Schould be independent as alias will not much work differenly. Just better integrated in parsong.

**Comment by paulkorir** [comment] 2022-09-27 09:18
I'm thinking of creating a parallel application (e.g. `SimpleParse2`) based on a fork of `master` since the author is unresponsive...

```shell
(ahds-py39) (base) ➜  ahds git:(master) ✗ twine upload dist/*0.2.4*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ahds-0.2.4-cp39-cp39-macosx_10_9_x86_64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB • 00:00 • 32.9 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                                        
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                               
         Invalid value for requires_dist. Error: Can't have direct dependency: 'simpleparse @ git+https://github.com/mcfletch/simpleparse'     
```

**Comment by hernot** [comment] 2022-09-27 09:56
Ok, let me know than I will redicrect my pull request to yours.

**Comment by paulkorir** [comment] 2022-10-04 12:54
We now have a new release `v0.2.4` which should have all the fixes. Thanks everyone.
